### PR TITLE
Waterdrips fix lab2

### PR DESCRIPTION
**Pull request by Waterdrips**
## Description

kubectl 1.18 changed run to create only a pod, not a pod wrapped in a deployment

## Motivation and Context

- [ ] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [ ] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks @Waterdrips

**Comment by alexellis** [comment]
@jrphub please could you try the instructions that @Waterdrips has just updated and report back?

**Comment by jrphub** [comment]
Sure, let me try . Thanks

**Comment by jrphub** [comment]
I have tried this, but it's not working. I am giving all details of my attempt. Please let me know if anything I am missing.
```kubectl version```
image

```kubectl -n openfaas get all```

image

image

```kubectl port-forward -n openfaas service/grafana 3000:3000```
image
Login to Grafana UI
image
Calling openfaas functions from UI
image
Function called Successfully
Coming to Grafana
Total Request - 200 OK is N/A
image

Checking Datasource of "Total request"
image

Data source is "faas"
Let's check "faas" datasource
image

Checking "Dashboards" tab
image

Opening Prometheus Dashboard
image

Opening "Grafana Metrics" Dashboard
image

Now coming back to "Total request", why is it N/A ? and how can I fix it?
image

**Comment by jrphub** [comment]
Grafana worked after exposing pod grafana
```kubectl -n openfaas expose pod grafana --type=NodePort --name=grafana```

**Pull request merged**
