### PR TITLE
Fix requestbin URL in lab7

### PR DESCRIPTION
**Pull request by jonatasbaldin**
Hey there 👋 

Request Bin moved to https://requestbin.com, this PR fixes the URLs used in the lab7.

### CODE REVIEW

**Comment by alexellis** [comment]
Thanks for letting us know.

**Comment by rgee0** [comment]
I was going to ask if there was an alternative that doesn't require people to log in

**Comment by alexellis** [comment]
@rgee0 I unchecked the private checkbox. Could you please add an instruction for this in a PR?

**Comment by rgee0** [comment]
https://github.com/openfaas/workshop/pull/150

**Pull request merged**
