### PR TITLE
Fix typo in python template code for lab3

### LINKED ISSUE #37: Lab 3 Documentation Glitch for Python3 Template
In Lab 3, the mentioned content of `handler.py` are: 

```python
def handle(req):
    """handle a request to the function
    Args:
        req (str): request body
    """

    print(req)
```

However, the actual content after the pull are: 

```python 
def handle(req):
    """handle a request to the function
    Args:
        req (str): request body
    """

    return req
```

the **print** behaviour is replaced by **return**. The documentation states `This function will just print the input, so it's effectively an echo function`, and since it is returned, I am not sure how to is redirected to stdout and where (probably needs a deeper look at the code)

### PR DESCRIPTION
**Pull request by zanetworker**
** What ** 
- The python template code in lab3 currently uses a `print(req)` 
- However, the actual `pull` command pulls the python template which includes a `return req` 
- This commit fixes #37  by adding the actual python code pulled by the `faas-cli` command

Signed-off-by: Adel Zaalouk <zanetworker@adelzaalouk.me>

### CODE REVIEW

**Comment by zanetworker** [comment]
I have replaced  `print` with `return` for lab 3 documentation in this  pull request, please review.

**Comment by alexellis** [comment]
@rgee0 there's a conflict on this now - could you see if this still applies and fix the typo if so?

**Comment by alexellis** [comment]
@zanetworker feel free to pick this up instead if you like - we have restructured the lab numbering.

**Comment by rgee0** [comment]
@alexellis these changes should have been picked up during the restructuring.

I’d appreciate it if @zanerworker could review master/lab3 now to confirm.

**Pull request closed without merging**
