### PR TITLE
Make minor fixes to openfaas workshop labs

### PR DESCRIPTION
**Pull request by codegold79**
## Description

Lab 7: fixed a typo by removing a back tick in a k8s command
Lab 11: updated link to Lab 5
Lab 5 (Japanese version): fixed broken image links

## Motivation and Context

Changes will make labs more correct and easier to follow.

Fixes issues #161 #164 #163 
- [x] I have raised an issue to propose this change ([required](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md))

## How Has This Been Tested?

I was able to click to images from my VS Code IDE, as well as go to the correct Lab 5 link.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I've read the [CONTRIBUTION](https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md) guide
- [x] I have signed-off my commits with `git commit -s`
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by codegold79** [comment]
Sorry, I got my test account mixed up in this PR. I need to redo something...

**Comment by codegold79** [comment]
@alexellis This PR is ready for review.

**Comment by alexellis** [comment]
Thanks @codegold79 - this looks good.

**Review by alexellis — APPROVED** [review]
LGTM

**Pull request merged**
