### PR TITLE
Fixed link of "translations/ja/lab10.md"

### PR DESCRIPTION
**Pull request by kakakakakku**
Hi, Thank you for awesome workshop 👍

# What

I found that link of `translations/ja/lab10.md` is wrong.
Fixed a little :)

### CODE REVIEW

**Comment by alexellis** [comment]
@kenfdev please could you double-check then I'll merge. 

Thank you for this PR!

**Comment by kenfdev** [comment]
Thanks @kakakakakku !

LGTM @alexellis 👍

**Comment by kakakakakku** [comment]
I posted blog for introduce workshop ( in Japanese ) 👍
Thanks !

- https://kakakakakku.hatenablog.com/entry/2019/01/31/082322

**Comment by kenfdev** [comment]
Awesome @kakakakakku :)

@alexellis This PR is GTG and can be merged. Thanks!

**Pull request merged**
